### PR TITLE
index.erb: sort jobs by `run_id`

### PR DESCRIPTION
**Pull request by carlocab**
This will make it easier to match runs in the orchestrator with PRs in
Homebrew/core, since it will list together VMs deployed for a specific
PR next to each other.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by Bo98** [comment]
Current order aligns with the order it will be processed, which seems a bit more useful. Sorting by run_id would put re-runs immediately to the top when it actually isn't processed first.

**Comment by carlocab** [comment]
I guess there should be a way to adjust the sort of the table...

**Comment by Bo98** [comment]
Sorting & filtering JS sounds like a nice feature

**Comment by carlocab** [comment]
Closing for now. Would be nice if this could be tracked in an issue:

> Sorting & filtering JS sounds like a nice feature

**Pull request closed without merging**
